# Generated by Django 5.0.6 on 2024-05-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_name', models.CharField(max_length=200)),
                ('usr_last_name', models.CharField(max_length=200)),
                ('usr_gener', models.CharField(max_length=50)),
                ('usr_email', models.EmailField(max_length=150)),
                ('usr_password', models.CharField(max_length=50)),
                ('usr_address', models.CharField(max_length=200)),
                ('usr_phone', models.CharField(max_length=200)),
                ('usr_last_access', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
