# Generated by Django 5.0.6 on 2024-05-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=200)),
                ('pro_precio', models.CharField(max_length=200)),
                ('pro_description', models.TextField(max_length=100)),
                ('pro_review', models.IntegerField()),
                ('pro_stock', models.PositiveIntegerField()),
                ('pro_image', models.CharField(max_length=100)),
                ('pro_category', models.CharField(max_length=200)),
            ],
        ),
    ]
