# Generated by Django 5.0.6 on 2024-06-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_pro_products_shoppingcart_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcartitem',
            old_name='ShoppingCart',
            new_name='cart',
        ),
    ]
