# Generated by Django 5.0.6 on 2024-06-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usr_name',
            new_name='username',
        ),
    ]
