# Generated by Django 5.0.6 on 2024-06-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_usr_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usr_password',
            new_name='password',
        ),
    ]
